### PR TITLE
Add devbin.lua

### PR DESCRIPTION
**Pull request by BlackDragon-B**
I would like to have this added to the rom so everyone can download from devbin easily. Its like pastebin but better.
https://devbin.dev/

### CODE REVIEW

**Comment by SquidDev** [comment]
Isn't this just a glorified `wget`?

**Comment by BlackDragon-B** [comment]
> Isn't this just a glorified `wget`?

No its a modified version of pastebin to work with devbin.dev i guess.

**Comment by SquidDev** [comment]
I guess my point is that given it doesn't support uploading, there's no big advantage of using it over `wget`.

**Comment by BlackDragon-B** [comment]
> I guess my point is that given it doesn't support uploading, there's no big advantage of using it over `wget`.

Yes your right. Closed.

**Pull request closed without merging**
