### PR TITLE
Add devbin.lua with put

### PR DESCRIPTION
**Pull request by BlackDragon-B**
This is a newer version of devbin.lua with modifications made by AlexDevs to be able to upload. 
/dev/bin is made by AlexDevs and the website: https://devbin.dev
I hope it will be added to the rom so its easier for poeple to access /dev/bin using a CC computer.

### CODE REVIEW

**Comment by Ale32bit** [comment]
Consider that /dev/bin is in beta and is subject to changes in the API

**Comment by BlackDragon-B** [comment]
> Consider that /dev/bin is in beta and is subject to changes in the API

then we ask to update.

**Comment by Wojbie** [comment]
I mean when creator of something tells you its in beta and unstable its usually a suggestion to hold your horses and wait.

**Comment by Lemmmy** [comment]
We'll review this when devbin is more mature

**Pull request closed without merging**
